# Generated by Django 4.1.4 on 2023-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_id',
        ),
        migrations.AddField(
            model_name='user',
            name='company_title',
            field=models.TextField(default='corp', verbose_name='id компании'),
        ),
    ]
