# Generated by Django 4.1.4 on 2023-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_role',
            field=models.CharField(choices=[('HR', 'HR'), ('CA', 'Candidate')], default='HR', max_length=255, verbose_name='Деятельность'),
        ),
    ]
