# Generated by Django 4.1.4 on 2023-01-16 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='stage',
            field=models.CharField(choices=[('Interview', 'Interview'), ('Task', 'Task'), ('Accept', 'Accept'), ('Refusal', 'Refusal')], default='Task', max_length=255, verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Почта кандидата'),
        ),
    ]
