# Generated by Django 4.1.4 on 2023-01-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_stage_alter_candidate_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='stage',
            field=models.CharField(choices=[('Interview', 'Interview'), ('Task', 'Task'), ('Accept', 'Accept'), ('Refusal', 'Refusal')], default='Interview', max_length=255, verbose_name='Стадия'),
        ),
    ]
