# Generated by Django 4.1.4 on 2023-01-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='owner_company',
        ),
    ]
