# Generated by Django 4.1.4 on 2023-01-16 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0004_alter_candidate_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user_email',
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кандидат'),
        ),
    ]
