# Generated by Django 4.1.4 on 2023-01-16 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_remove_candidate_user_email_candidate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ManyToManyField(related_name='candidates', to=settings.AUTH_USER_MODEL, verbose_name='Кандидат'),
        ),
    ]
