# Generated by Django 4.1.4 on 2023-01-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_remove_candidate_user_candidate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='user_email',
        ),
    ]
