# Generated by Django 4.1.4 on 2023-01-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_rename_user_email_candidate_candidate_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate_email',
            new_name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_candidate',
            field=models.EmailField(max_length=255, null=True, verbose_name='Почта'),
        ),
    ]
