# Generated by Django 4.1.4 on 2023-01-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_rename_candidate_email_candidate_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate',
        ),
    ]
