# Generated by Django 4.1.4 on 2023-01-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0010_remove_candidate_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCandidate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('email_candidate', models.EmailField(max_length=255, null=True, verbose_name='Почта')),
                ('created_at', models.DateField(verbose_name='Время создания')),
                ('stage', models.CharField(choices=[('Interview', 'Interview'), ('Task', 'Task'), ('Accept', 'Accept'), ('Refusal', 'Refusal')], default='Interview', max_length=255, verbose_name='Стадия')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Кандидат',
                'verbose_name_plural': 'historical Кандидаты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
