# Generated by Django 4.1.4 on 2023-01-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='candidates_vacancy',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Кандидат'),
        ),
    ]
