# Generated by Django 4.1.4 on 2023-01-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidate_user_email'),
        ('vacancy', '0002_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Кандидат'),
        ),
    ]
