# Generated by Django 4.1.4 on 2023-01-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_remove_candidate_user_email_candidate_user'),
        ('vacancy', '0004_alter_vacancy_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='candidate',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='candidate',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='candidate.candidate', verbose_name='Кандидат'),
        ),
    ]
