# Generated by Django 4.1.4 on 2023-01-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_remove_vacancy_candidate_vacancy_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['id', 'title'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
