# Generated by Django 4.1.4 on 2023-01-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_historicalcandidate'),
        ('vacancy', '0007_historicalvacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvacancy',
            name='link_vacancy',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidate',
            field=models.ManyToManyField(blank=True, null=True, related_name='candidates', to='candidate.candidate', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='link_vacancy',
            field=models.TextField(verbose_name='Ссылка'),
        ),
    ]
