# Generated by Django 4.1.4 on 2023-01-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_historicalcandidate'),
        ('vacancy', '0008_alter_historicalvacancy_link_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='candidate',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='candidate.candidate', verbose_name='Кандидат'),
        ),
    ]
