# Generated by Django 4.1.4 on 2023-01-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_time', models.DateTimeField(verbose_name='время занятое')),
                ('free_time', models.DateTimeField(verbose_name='время свободное')),
                ('candidates', models.TextField(verbose_name='Кандидат')),
            ],
        ),
    ]
