# Generated by Django 4.1.4 on 2023-01-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('meeting_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingtime',
            options={'verbose_name': 'Выбор времени'},
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название встречи'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='candidates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Кандидат'),
        ),
    ]
