# Generated by Django 4.1.4 on 2023-01-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_time', '0005_historicalmeetingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmeetingtime',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='meetingtime',
            name='close_time',
        ),
    ]
