# Generated by Django 4.1.4 on 2023-01-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerCorp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercorp',
            name='company',
            field=models.TextField(null=True, verbose_name='Id пользователя'),
        ),
        migrations.AlterField(
            model_name='ownercorp',
            name='user',
            field=models.TextField(null=True, verbose_name='Id пользователя'),
        ),
    ]
