# Generated by Django 4.1.4 on 2022-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('answer', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=30)),
            ],
        ),
    ]
