# Generated by Django 4.1.4 on 2023-01-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_completed_task_update_at_alter_task_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
