# Generated by Django 4.1.4 on 2023-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.CharField(choices=[('PY', 'PY'), ('JS', 'JS'), ('PHP', 'PHP'), ('HTML', 'HTML')], default='PY', max_length=255, verbose_name='Выбор языка'),
        ),
    ]
