# Generated by Django 4.1.4 on 2023-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
