# Generated by Django 4.1.4 on 2023-01-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id', 'title'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
