# Generated by Django 4.1.4 on 2023-01-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_user_company_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='user',
        ),
    ]
