# Generated by Django 4.1.4 on 2023-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_remove_vacancy_candidate_vacancy_candidate'),
        ('company', '0004_rename_user_id_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vacancies',
            field=models.ManyToManyField(related_name='Companies', to='vacancy.vacancy', verbose_name='Вакансии'),
        ),
    ]
