# Generated by Django 4.1.4 on 2023-01-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_historicalvacancy'),
        ('company', '0006_historicalcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vacancies',
            field=models.ManyToManyField(blank=True, related_name='Companies', to='vacancy.vacancy', verbose_name='Вакансии'),
        ),
    ]
